Terraform unknown SetNestedAttribute panic
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/709

```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^TestSetUnknownResource_basic$ github.com/bflad/terraform-provider-framework/internal/provider

--- FAIL: TestSetUnknownResource_basic (0.22s)
    /Users/bflad/src/github.com/bflad/terraform-provider-framework/internal/provider/set_unknown_resource_test.go:10: Step 1/2 error: Error running pre-apply refresh: exit status 11

        !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

        Terraform crashed! This is always indicative of a bug within Terraform.
        Please report the crash with Terraform[1] so that we can fix this.

        When reporting bugs, please include your terraform version, the stack trace
        shown below, and any additional information which may help replicate the issue.

        [1]: https://github.com/hashicorp/terraform/issues

        !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

        value is not known
        goroutine 78 [running]:
        runtime/debug.Stack()
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
        runtime/debug.PrintStack()
        	/usr/local/go/src/runtime/debug/stack.go:16 +0x1c
        github.com/hashicorp/terraform/internal/logging.PanicHandler()
        	/Users/distiller/project/project/internal/logging/panic.go:55 +0x170
        panic({0x1065ae5e0, 0x106a6f0a0})
        	/usr/local/go/src/runtime/panic.go:890 +0x258
        github.com/zclconf/go-cty/cty.Value.LengthInt({{{0x106a99e78?, 0x14000c04180?}}, {0x106662b20?, 0x107e932a0?}})
        	/Users/distiller/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/value_ops.go:1063 +0x218
        github.com/hashicorp/terraform/internal/plans/objchange.assertPlannedObjectValid(0x1400040de40, {{{0x0?, 0x0?}}, {0x0?, 0x0?}}, {{{0x106a99e78?, 0x14000c042b0?}}, {0x10699b560?, 0x14000655518?}}, {{{0x106a99e78?, ...}}, ...}, ...)
        	/Users/distiller/project/project/internal/plans/objchange/plan_valid.go:421 +0x418
        github.com/hashicorp/terraform/internal/plans/objchange.assertPlannedValueValid(0x140004150c0, {{{0x0?, 0x0?}}, {0x0?, 0x0?}}, {{{0x106a99e78?, 0x14000c042b0?}}, {0x10699b560?, 0x14000655518?}}, {{{0x106a99e78?, ...}}, ...}, ...)
        	/Users/distiller/project/project/internal/plans/objchange/plan_valid.go:308 +0x758
        github.com/hashicorp/terraform/internal/plans/objchange.assertPlannedAttrValid({0x14000406030, 0x14}, 0x140004150c0, {{{0x106a99e40?, 0x1400089e970?}}, {0x0?, 0x0?}}, {{{0x106a99e40?, 0x14000c042e0?}}, {0x1066907e0?, ...}}, ...)
        	/Users/distiller/project/project/internal/plans/objchange/plan_valid.go:264 +0x234
        github.com/hashicorp/terraform/internal/plans/objchange.assertPlannedAttrsValid(0x106a99e40?, {{{0x106a99e40?, 0x1400089e970?}}, {0x0?, 0x0?}}, {{{0x106a99e40?, 0x14000c042e0?}}, {0x1066907e0?, 0x140008ed1d0?}}, {{{0x106a99e40?, ...}}, ...}, ...)
        	/Users/distiller/project/project/internal/plans/objchange/plan_valid.go:249 +0x188
        github.com/hashicorp/terraform/internal/plans/objchange.assertPlanValid(0x140004093b0, {{{0x106a99e40?, 0x1400089e970?}}, {0x0?, 0x0?}}, {{{0x106a99e40?, 0x14000c042e0?}}, {0x1066907e0?, 0x140008ed1d0?}}, {{{0x106a99e40?, ...}}, ...}, ...)
        	/Users/distiller/project/project/internal/plans/objchange/plan_valid.go:57 +0x2ac
        github.com/hashicorp/terraform/internal/plans/objchange.AssertPlanValid(...)
        	/Users/distiller/project/project/internal/plans/objchange/plan_valid.go:36
        github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0x140001603c0, {0x106aaf6f8, 0x140009e4380}, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0?})
        	/Users/distiller/project/project/internal/terraform/node_resource_abstract_instance.go:830 +0x153c
        github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0x1400064f940, {0x106aaf6f8, 0x140009e4380})
        	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:223 +0xa6c
        github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x106aaf6f8?, 0x140009e4380?}, 0x80?)
        	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:60 +0x7c
        github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x140009ea0f0, {0x106aaf6f8, 0x140009e4380}, {0x11001f230, 0x1400064f940})
        	/Users/distiller/project/project/internal/terraform/graph_walk_context.go:136 +0xa8
        github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x106a1aec0, 0x1400064f940})
        	/Users/distiller/project/project/internal/terraform/graph.go:75 +0x238
        github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x1400081e600, {0x106a1aec0, 0x1400064f940}, 0x1400064fa40)
        	/Users/distiller/project/project/internal/dag/walk.go:381 +0x2e0
        created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        	/Users/distiller/project/project/internal/dag/walk.go:304 +0xbf0
FAIL
FAIL	github.com/bflad/terraform-provider-framework/internal/provider	1.002s
FAIL
```