Reproduce SetNestedAttribute Inconsistent Apply After Element Removal and In-Place Update
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/709

```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^TestSetUnknownResource_basic$ github.com/bflad/terraform-provider-framework/internal/provider

--- FAIL: TestSetUnknownResource_basic (0.63s)
    /Users/bflad/src/github.com/bflad/terraform-provider-framework/internal/provider/set_unknown_resource_test.go:10: Step 2/2 error: Error running apply: exit status 1

        Error: Provider produced inconsistent result after apply

        When applying changes to framework_set_unknown.test, provider
        "provider[\"registry.terraform.io/hashicorp/framework\"]" produced an
        unexpected new value: .set_nested_attribute: planned set element
        cty.ObjectVal(map[string]cty.Value{"id":cty.StringVal("id-456"),
        "name":cty.StringVal("name-123"), "permission":cty.StringVal("permission2")})
        does not correlate with any element in actual.

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
FAIL
FAIL	github.com/bflad/terraform-provider-framework/internal/provider	1.525s
FAIL
```